### ISSUE TITLE
bug: "E-commerce Product Description" example not working

### ISSUE THREAD

**Issue by marelix2** [callstackincubator/fabrice-ai#103]
Steps to reproduce: 
1. npx create-fabrice-ai
2. Choose a template to get started:
│  E-commerce Product Description - Convert product photos into compelling store listings
3. cd fabrice-ai-example
4. npm install
5. node --import=tsx src/ecommerce_product_description.ts 

Result:
```
 node --import=tsx src/ecommerce_product_description.ts
🕒 Distributing the task...
Request: Analyze the picture './example/assets/example-sneakers.jpg' to identify and list all visible technical features of the sneakers, such as color, size, material, and brand.
🛠️ Agent "Technical expert" is beginning to work on the task
Step details: Analyze the picture './example/assets/example-sneakers.jpg' to identify and list all visible technical features of the sneakers, such as color, size, material, and brand.
🔄 Agent "Technical expert" is moving to the next step
Step details: Use the 'functions.visionTool' to analyze the image for technical details.
🔧 Agent "Technical expert" is calling tools
Tools: visionTool
node:internal/fs/promises:639
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open './example/assets/example-sneakers.jpg'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1249:14)
    at async encodeImage (file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/@fabrice-ai/tools/dist/vision.js:8:25)
    at async Object.execute (file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/@fabrice-ai/tools/dist/vision.js:63:75)
    at async file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/fabrice-ai/dist/teamwork.js:167:25
    at async Promise.all (index 0)
    at async runTools (file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/fabrice-ai/dist/teamwork.js:163:25)
    at async nextTick (file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/fabrice-ai/dist/teamwork.js:286:35)
    at async iterate (file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/fabrice-ai/dist/teamwork.js:324:23)
    at async teamwork (file:///Users/michalrusinek/repos/ai-investigations/fabrice-ai/fabrice-ai-example/node_modules/fabrice-ai/dist/teamwork.js:351:31) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './example/assets/example-sneakers.jpg'
}

Node.js v20.15.0
```

<img width="620" alt="Screenshot 2024-12-12 at 09 46 53" src="https://github.com/user-attachments/assets/eca8f3e9-6598-462d-845b-ccdacf07e659" />

I've tried to modify the path to the image, moved it directly to ecommerce_product_description.is directory. I tried to use my image example too. Nothing seems to work

**Comment by pkarw** [comment]
Hey @marelix2! Thanks for raising this issue. The fix is on the way: https://github.com/callstackincubator/fabrice-ai/pull/104

Quick fix:

Change the relative path in the `src/ecommerce_product_description.ts` - line 27, from:

```ts
const productDescriptionWorkflow = workflow({
  members: [techExpert, marketingManager],
  description: `
    Based on the picture './example/assets/example-sneakers.jpg' make the eCommerce product to 
    list this product on the website.
```

... to fixed one:

```ts
const productDescriptionWorkflow = workflow({
  members: [techExpert, marketingManager],
  description: `
    Based on the picture '${path.resolve(__dirname, '../assets/example-sneakers.jpg')}' make the eCommerce product to 
    list this product on the website.
```

**Comment by pkarw** [comment]
Hey @marelix2! Thanks for raising this issue. The fix is on the way: https://github.com/callstackincubator/fabrice-ai/pull/104

Quick fix:

Change the relative path in the `src/ecommerce_product_description.ts` - line 27, from:

```ts
const productDescriptionWorkflow = workflow({
  members: [techExpert, marketingManager],
  description: `
    Based on the picture './example/assets/example-sneakers.jpg' make the eCommerce product to 
    list this product on the website.
```

... to fixed one:

```ts
const productDescriptionWorkflow = workflow({
  members: [techExpert, marketingManager],
  description: `
    Based on the picture '${path.resolve(__dirname, '../assets/example-sneakers.jpg')}' make the eCommerce product to 
    list this product on the website.
```
