### ISSUE TITLE
bug: GitHub Trending example does not deploy from template

### ISSUE THREAD

**Issue by mdjastrzebski** [callstackincubator/fabrice-ai#89]
## Summary

Tried to deploy `GitHub Trending` example using `npx create-fabrice-ai` but it fails with following error.

Error details:
```
Other % npx create-fabrice-ai
Need to install the following packages:
create-fabrice-ai@0.4.1
Ok to proceed? (y) y


  ███████╗ █████╗ ██████╗ ██████╗ ██╗ ██████╗███████╗
  ██╔════╝██╔══██╗██╔══██╗██╔══██╗██║██╔════╝██╔════╝
  █████╗  ███████║██████╔╝██████╔╝██║██║     █████╗  
  ██╔══╝  ██╔══██║██╔══██╗██╔══██╗██║██║     ██╔══╝  
  ██║     ██║  ██║██████╔╝██║  ██║██║╚██████╗███████╗
  ╚═╝     ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝

┌  (c) 2024 Callstack Research Team
│
◇  How would you like to name your project?
│  fabrice-test
│
◇  Choose a template to get started:
│  GitHub Trending - Track and summarize hot Python projects on GitHub
│
◐  Downloading template.mv: rename /var/folders/0q/fsh5sbmd1y5ff77l1y1w7fw00000gn/T/example/src/tools/firecrawl.ts to /Users/maciej/Development/Other/fabrice-test/src/tools/firecrawl.ts: No such file or directory
▲  Something went wrong
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: mv /var/folders/0q/fsh5sbmd1y5ff77l1y1w7fw00000gn/T/example/src/tools/firecrawl.ts /Users/maciej/Development/Other/fabrice-test/src/tools/firecrawl.ts
mv: rename /var/folders/0q/fsh5sbmd1y5ff77l1y1w7fw00000gn/T/example/src/tools/firecrawl.ts to /Users/maciej/Development/Other/fabrice-test/src/tools/firecrawl.ts: No such file or directory

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at downloadAndExtractTemplate (file:///Users/maciej/.npm/_npx/8f5c249ed62470b2/node_modules/create-fabrice-ai/dist/index.js:39:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/maciej/.npm/_npx/8f5c249ed62470b2/node_modules/create-fabrice-ai/dist/index.js:147:1 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(189) [Uint8Array] [
      109, 118,  58,  32, 114, 101, 110,  97, 109, 101,  32,  47,
      118,  97, 114,  47, 102, 111, 108, 100, 101, 114, 115,  47,
       48, 113,  47, 102, 115, 104,  53, 115,  98, 109, 100,  49,
      121,  53, 102, 102,  55,  55, 108,  49, 121,  49, 119,  55,
      102, 119,  48,  48,  48,  48,  48, 103, 110,  47,  84,  47,
      101, 120,  97, 109, 112, 108, 101,  47, 115, 114,  99,  47,
      116, 111, 111, 108, 115,  47, 102, 105, 114, 101,  99, 114,
       97, 119, 108,  46, 116, 115,  32, 116, 111,  32,  47,  85,
      115, 101, 114, 115,
      ... 89 more items
    ]
  ],
  pid: 85058,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(189) [Uint8Array] [
    109, 118,  58,  32, 114, 101, 110,  97, 109, 101,  32,  47,
    118,  97, 114,  47, 102, 111, 108, 100, 101, 114, 115,  47,
     48, 113,  47, 102, 115, 104,  53, 115,  98, 109, 100,  49,
    121,  53, 102, 102,  55,  55, 108,  49, 121,  49, 119,  55,
    102, 119,  48,  48,  48,  48,  48, 103, 110,  47,  84,  47,
    101, 120,  97, 109, 112, 108, 101,  47, 115, 114,  99,  47,
    116, 111, 111, 108, 115,  47, 102, 105, 114, 101,  99, 114,
     97, 119, 108,  46, 116, 115,  32, 116, 111,  32,  47,  85,
    115, 101, 114, 115,
    ... 89 more items
  ]
}
```

When checking the content of temp directory (), I get this:
```
Other % ls /var/folders/0q/fsh5sbmd1y5ff77l1y1w7fw00000gn/T/example/src/tools
askUser.ts	wikipedia.ts
```

**Comment by mdjastrzebski** [comment]
Seems like `create-fabric-ai` is downloading `'https://github.com/callstackincubator/fabrice-ai/archive/refs/heads/main.tar.gz',`, which after unpacking does not contain the `firecrawl.ts` file:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/5d2ea681-f4eb-4541-9054-a2b282b2aa1d">

**Comment by pkarw** [comment]
Thanks 🙏 yes, it got moved to the 'fabrice-ai/tools' package. Will fix it shortly. Stay tuned.

**Comment by mdjastrzebski** [comment]
good to know, I though there might be some caching involved for downloading `main` code snapshots.

**Comment by pkarw** [comment]
@mdjastrzebski fixed with https://github.com/callstackincubator/fabrice-ai/pull/90 + released to `npm`, so please go ahead and try if it works for you now.

**Comment by mdjastrzebski** [comment]
It now deploys, but does not run:
```
fabrice-test-3 % bun src/github_trending.ts
error: Cannot find module "@clack/prompts" from "/Users/maciej/Development/Other/fabrice-test-3/node_modules/@fabrice-ai/tools/src/utils.ts"
```

**Comment by mdjastrzebski** [comment]
@pkarw https://github.com/callstackincubator/fabrice-ai/pull/96
